apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdc-operator
  namespace: multicluster-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8sdc-operator
  template:
    metadata:
      labels:
        name: k8sdc-operator
    spec:
      serviceAccountName: icamklust
      containers:
        - name: k8sdc-operator
          # Replace this with the built image name
          image: MY_REGISTRY/multicluster-endpoint/k8sdc-operator:APM_202003092352
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k8sdc-operator"
 